import { StyleSheet } from 'react-native';

export const makeStyles = (colors: any) => StyleSheet.create({
  container:          { flex: 1, backgroundColor: colors.background },
  header:             { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 8, paddingBottom: 6, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border },
  selectionHeader:    { backgroundColor: colors.surfaceAlt },
  backBtn:            { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  backArrow:          { fontSize: 30, lineHeight: 30, color: colors.textPrimary },
  headerCenter:       { flex: 1, alignItems: 'center' },
  headerTitle:        { fontSize: 17, fontWeight: '600', color: colors.textPrimary },
  headerSub:          { fontSize: 12, color: colors.textSecondary, marginTop: 1 },
  headerCallBtn:      { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  selectionHeaderCount: { flex: 1, minWidth: 0, justifyContent: 'center' },
  selectionHeaderTitle: { color: colors.textPrimary, fontSize: 18, fontWeight: '700' },
  content:            { paddingTop: 12, paddingHorizontal: 8 },
  previewCard:        { backgroundColor: colors.background, borderRadius: 0, padding: 0, marginTop: 0, position: 'relative', overflow: 'hidden' },
  chatSection:        { width: '100%', marginBottom: 0 },
  chatRowLeft:        { width: '100%', alignItems: 'flex-start', marginBottom: 0 },
  chatRowRight:       { width: '100%', alignItems: 'flex-end', marginBottom: 0 },
  chatBubbleLeft:     { backgroundColor: colors.surfaceAlt, borderRadius: 14, borderTopLeftRadius: 4, maxWidth: '80%', overflow: 'hidden' },
  chatBubbleRight:    { backgroundColor: colors.border, borderRadius: 14, borderTopRightRadius: 4, maxWidth: '80%', overflow: 'hidden' },
  chatText:           { color: colors.textPrimary, fontSize: 13, lineHeight: 18, paddingHorizontal: 12, paddingTop: 10, paddingBottom: 2 },
  chatTextRight:      { color: colors.textPrimary, fontSize: 13, lineHeight: 18, paddingHorizontal: 12, paddingTop: 10, paddingBottom: 2, marginBottom: 0 },
  chatTimeLeft:       { color: colors.textMuted, fontSize: 10, marginTop: 2 },
  chatTimeRight:      { color: colors.textMuted, fontSize: 10, marginTop: 2, textAlign: 'right' },
  dateDivider:        { alignItems: 'center', marginVertical: 8 },
  dateDividerPill:    { backgroundColor: colors.surfaceAlt, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 5, borderWidth: 0.5, borderColor: colors.border },
  dateDividerText:    { fontSize: 12, color: colors.textSecondary },
  stickyPillWrap:     { position: 'absolute', top: 0, left: 0, right: 0, alignItems: 'center', zIndex: 999, paddingTop: 6 },
  stickyPill:         { backgroundColor: colors.surfaceAlt, borderRadius: 10, paddingHorizontal: 14, paddingVertical: 5, borderWidth: 0.5, borderColor: colors.border },
  stickyPillText:     { fontSize: 12, color: colors.textSecondary },
  bottomInputArea:    { backgroundColor: colors.background, paddingHorizontal: 10, paddingTop: 6, paddingBottom: 8, zIndex: 100, elevation: 100 },
  chatInputWrap:      { width: '100%', alignItems: 'stretch', position: 'relative' },
  chatInput:          { backgroundColor: colors.inputBackground, borderColor: colors.inputBorder, borderWidth: 1, borderRadius: 12, color: colors.inputText, fontSize: 13, paddingHorizontal: 12, paddingRight: 42, paddingVertical: 10, minHeight: 44 },
  chatSendIconButton: { position: 'absolute', right: 10, top: 0, bottom: 0, justifyContent: 'center', paddingHorizontal: 2 },
  starredBackdrop:    { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,0.55)' },
  starredSheet:       { maxHeight: '70%', backgroundColor: colors.surface, borderTopLeftRadius: 16, borderTopRightRadius: 16, borderWidth: 1, borderColor: colors.border, overflow: 'hidden' },
  starredHeader:      { minHeight: 54, flexDirection: 'row', alignItems: 'center', paddingLeft: 18, paddingRight: 8, borderBottomWidth: 1, borderBottomColor: colors.border },
  starredTitle:       { flex: 1, color: colors.textPrimary, fontSize: 17, fontWeight: '700' },
  starredCloseBtn:    { width: 42, height: 42, alignItems: 'center', justifyContent: 'center' },
  starredList:        { maxHeight: 430 },
  starredListContent: { paddingVertical: 6 },
  starredEmpty:       { minHeight: 150, alignItems: 'center', justifyContent: 'center', gap: 10, paddingHorizontal: 24 },
  starredEmptyText:   { color: colors.textSecondary, fontSize: 14, textAlign: 'center' },
  starredItem:        { flexDirection: 'row', alignItems: 'flex-start', gap: 10, paddingHorizontal: 16, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border },
  starredItemBody:    { flex: 1, minWidth: 0 },
  starredItemMeta:    { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  starredSender:      { flex: 1, color: colors.textPrimary, fontSize: 13, fontWeight: '700' },
  starredTime:        { color: colors.textMuted, fontSize: 11 },
  starredPreview:     { color: colors.textSecondary, fontSize: 13, lineHeight: 18 },
});
