import { StyleSheet } from 'react-native';
import type { AppColors } from '../../utils/themeColors';

export default (colors: AppColors, topInset: number) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background, paddingTop: topInset },
    actionWrap: { position: 'absolute', top: topInset + 8, right: 12, flexDirection: 'row', alignItems: 'center', gap: 6, zIndex: 10, paddingVertical: 4, paddingHorizontal: 4, borderRadius: 30 },
    actionWrapScrolled: { backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 8, elevation: 10 },
    iconBtn: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
    iconBtnScrolled: { backgroundColor: colors.surfaceAlt },
    iconBtnActive: { backgroundColor: 'rgba(96,165,250,0.15)' },
    searchPill: { height: 34, flexDirection: 'row', alignItems: 'center', overflow: 'hidden', borderRadius: 17 },
    searchPillOpen: { backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)' },
    searchInput: { flex: 1, color: colors.textPrimary, fontSize: 14, paddingLeft: 12, paddingRight: 4, height: 34 },
    filterDropdown: { position: 'absolute', top: topInset + 54, right: 12, backgroundColor: colors.surfaceAlt, borderRadius: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.1)', zIndex: 20, minWidth: 140, overflow: 'hidden', elevation: 12 },
    filterOption: { paddingVertical: 11, paddingHorizontal: 16 },
    filterOptionActive: { backgroundColor: 'rgba(96,165,250,0.15)' },
    filterOptionText: { color: colors.textSecondary, fontSize: 14, fontWeight: '500' },
    filterOptionTextActive: { color: '#60a5fa', fontWeight: '700' },
    listContent: { paddingTop: 56, paddingBottom: 110 },
    emergencyTabList: { paddingTop: 56, paddingBottom: 110 },
    emergencyCard: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginHorizontal: 12, marginVertical: 4 },
    emergencyIcon: { marginRight: 14 },
    emergencyActionBtn: { width: 50, height: 50, borderRadius: 25, backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.borderLight, alignItems: 'center', justifyContent: 'center' },
    row: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 12, borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginHorizontal: 12, marginVertical: 4 },
    contactCard: { borderRadius: 12, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.surface, marginHorizontal: 12, marginVertical: 4, paddingHorizontal: 16, paddingVertical: 12 },
    contactHeaderRow: { flexDirection: 'row', alignItems: 'center', width: '100%' },
    contactExpandedArea: { marginTop: 10, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10, width: '100%' },
    contactLabel: { color: colors.textSecondary, fontSize: 12, marginTop: 1 },
    contactDetailText: { color: colors.textSecondary, fontSize: 13, lineHeight: 18, marginBottom: 4 },
    avatar: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surfaceAlt, marginRight: 12 },
    avatarPinned: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: '#dc2626', marginRight: 12 },
    avatarText: { color: '#fff', fontWeight: '700' },
    rowCenter: { flex: 1 },
    rowName: { color: colors.textPrimary, fontSize: 16, fontWeight: '600' },
    rowSub: { color: colors.textSecondary, fontSize: 12, marginTop: 2 },
    emptyText: { color: colors.textMuted, textAlign: 'center', marginTop: 24 },
    dateSeparator: { color: colors.textMuted, fontSize: 13, fontWeight: '600', paddingHorizontal: 16, paddingTop: 20, paddingBottom: 8, letterSpacing: 0.2 },
    recentMeta: { flexDirection: 'row', alignItems: 'center', gap: 3, marginTop: 3 },
    recentCount: { color: colors.textMuted, fontSize: 11 },
    recentDate: { color: colors.textSecondary, fontSize: 12, marginLeft: 4 },
    dialerContainer: { flex: 1, paddingTop: 56, paddingBottom: 90 },
    tooltipOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 15 },
    tooltipBubble: { position: 'absolute', top: topInset + 62, right: 48, backgroundColor: colors.surfaceAlt, borderRadius: 10, borderWidth: 1, borderColor: 'rgba(255,255,255,0.12)', paddingHorizontal: 14, paddingVertical: 10, maxWidth: 220, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.35, shadowRadius: 10, elevation: 14 },
    tooltipText: { color: colors.textPrimary, fontSize: 13, lineHeight: 18 },
    tooltipArrow: { position: 'absolute', top: -6, right: 20, width: 12, height: 12, backgroundColor: colors.surfaceAlt, transform: [{ rotate: '45deg' }], borderLeftWidth: 1, borderTopWidth: 1, borderColor: 'rgba(255,255,255,0.12)' },
    // pill bar styles moved to FloatingTabBar component
  });
