import { StyleSheet } from 'react-native';
import { AppColors } from '../../utils/themeColors';

export default function makeCheckInSettingsStyles(colors: AppColors, topInset: number) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: topInset + 8,
      paddingBottom: 12,
      backgroundColor: colors.surface,
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
    },
    backButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    headerSpacer: { width: 40, height: 40 },
    headerTitle: { color: colors.textPrimary, fontSize: 18, fontWeight: 'bold' },
    scroll: { paddingVertical: 16, paddingBottom: 100 },
    section: { marginBottom: 24, paddingHorizontal: 16 },
    scheduleHeader: { color: colors.textSecondary, fontSize: 13, fontWeight: '600', marginTop: 4, marginBottom: 12 },
    scheduleCard: {
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 16,
      paddingTop: 16,
      paddingBottom: 8,
      marginTop: 12,
    },
    sectionTitle: { color: colors.textPrimary, fontSize: 15, fontWeight: '700', marginBottom: 12 },
    subSectionTitle: { color: colors.textSecondary, fontSize: 12, fontWeight: '600', textTransform: 'uppercase', letterSpacing: 0.8, marginTop: 8, marginBottom: 6 },
    row: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.surface,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
    },
    label: { color: colors.textPrimary, fontSize: 15, flex: 1 },
    sublabel: { color: colors.textMuted, fontSize: 12, marginTop: 2 },
    sliderRow: {
      backgroundColor: colors.surface,
      padding: 16,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      marginBottom: 8,
    },
    sliderLabel: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    value: { color: colors.accent, fontSize: 14, fontWeight: '600' },
    input: {
      backgroundColor: colors.inputBackground,
      color: colors.inputText,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.inputBorder,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      minHeight: 60,
      textAlignVertical: 'top',
      marginBottom: 8,
    },
    saveBtn: {
      backgroundColor: colors.accent,
      paddingVertical: 16,
      paddingHorizontal: 32,
      borderRadius: 50,
      borderWidth: 1.5,
      borderColor: 'rgba(255,255,255,0.3)',
    },
    saveBtnText: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
    disabledBtn: { opacity: 0.5 },
    enableRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.surface,
      paddingHorizontal: 16,
      paddingVertical: 16,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: colors.border,
      marginTop: 12,
    },
    enableLabel: { color: colors.textPrimary, fontSize: 17, fontWeight: 'bold' },
    timeRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
    },
    timeBlock: {
      flex: 1,
      backgroundColor: colors.surface,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: colors.border,
      marginHorizontal: 4,
    },
    timeLabel: { color: colors.textMuted, fontSize: 12, marginBottom: 6 },
    timeUnit: { color: colors.textMuted, fontSize: 15, marginLeft: 2 },
    timeInputRow: { flexDirection: 'row', alignItems: 'center' },
    timeInput: { backgroundColor: colors.inputBackground, color: colors.inputText, borderRadius: 8, borderWidth: 1, borderColor: colors.inputBorder, paddingHorizontal: 10, paddingVertical: 6, fontSize: 22, fontWeight: 'bold', width: 60, textAlign: 'center' },
    intervalCard: { backgroundColor: colors.surfaceAlt, borderRadius: 8, borderWidth: 1, borderColor: colors.borderLight, padding: 16, marginBottom: 8, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    intervalTextCol: { flex: 1, marginRight: 12 },
    intervalTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
    intervalLabel: { color: colors.textPrimary, fontSize: 15, fontWeight: '500', flex: 1, marginRight: 12 },
    intervalHint: { color: colors.textMuted, fontSize: 12, lineHeight: 16 },
    intervalRow: { flexDirection: 'row', alignItems: 'center' },
    intervalControl: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surface, borderRadius: 8, borderWidth: 1, borderColor: colors.inputBorder, paddingHorizontal: 10, paddingVertical: 8 },
    intervalInput: { fontSize: 15, fontWeight: '500', color: colors.inputText, textAlign: 'center', minWidth: 24, padding: 0 },
    unitLabel: { color: colors.textSecondary, fontSize: 15, marginLeft: 2 },
    desc: { color: colors.textMuted, fontSize: 14, marginBottom: 16, lineHeight: 20 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center' },
    infoModal: { backgroundColor: colors.surface, borderRadius: 12, padding: 24, paddingTop: 16, width: '85%', maxWidth: 380, borderWidth: 1, borderColor: colors.border },
    infoClose: { alignSelf: 'flex-end', padding: 4, marginBottom: 8 },
    infoText: { color: colors.textPrimary, fontSize: 15, lineHeight: 22 },
  });
}
