import { StyleSheet } from 'react-native';
import { useTheme } from '../../context/ThemeContext';

export const makeEmergencyCallStyles = (colors: ReturnType<typeof useTheme>['colors']) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    content: { paddingTop: 12, paddingHorizontal: 8 },
    headerBar: {},
    endCallButton: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', backgroundColor: '#DC2626', borderWidth: 1, borderColor: 'rgba(255,255,255,0.4)', paddingHorizontal: 20, paddingVertical: 7, borderRadius: 20, width: 100, elevation: 5, shadowColor: colors.background, shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.3, shadowRadius: 4 },
    endCallArrow: { color: colors.textPrimary, fontSize: 16, fontWeight: 'bold' },
    endCallText: { color: colors.textPrimary, fontSize: 14, fontWeight: '600' },
    title: { fontSize: 28, fontWeight: 'bold', color: colors.textPrimary, marginBottom: 8 },
    description: { fontSize: 14, color: colors.textMuted, marginBottom: 24 },
    card: { backgroundColor: colors.surface, borderRadius: 12, padding: 20, marginBottom: 16, borderWidth: 1, borderColor: colors.border },
    cardTitle: { fontSize: 18, fontWeight: '600', color: colors.textPrimary, marginBottom: 8 },
    cardDescription: { fontSize: 14, color: colors.textMuted, marginBottom: 16, lineHeight: 20 },
    button: { backgroundColor: colors.accent, borderRadius: 8, paddingVertical: 14, alignItems: 'center' },
    buttonSecondary: { backgroundColor: '#7C3AED' },
    buttonDisabled: { opacity: 0.5 },
    buttonText: { color: colors.textPrimary, fontSize: 16, fontWeight: '600' },
    resultCard: { backgroundColor: colors.surface, borderRadius: 12, padding: 20, marginTop: 8, borderWidth: 2, borderColor: '#10B981' },
    resultTitle: { fontSize: 20, fontWeight: 'bold', color: '#10B981', marginBottom: 16 },
    resultRow: { marginBottom: 12 },
    resultLabel: { fontSize: 12, color: colors.textMuted, marginBottom: 4 },
    resultValue: { fontSize: 14, color: colors.textPrimary, fontFamily: 'monospace' },
    buttonRow: { flexDirection: 'row', marginTop: 12, gap: 8 },
    retryButton: { flex: 1, padding: 12, backgroundColor: colors.accent, borderRadius: 8, alignItems: 'center' },
    retryButtonText: { color: colors.textPrimary, fontSize: 14, fontWeight: '600' },
    viewXmlButton: { flex: 1, padding: 12, backgroundColor: colors.surfaceAlt, borderRadius: 8, alignItems: 'center' },
    viewXmlText: { color: colors.accentLight, fontSize: 14, fontWeight: '500' },
    accuracyLabel: { fontSize: 13, color: colors.accentLight, textAlign: 'center', marginTop: -8, marginBottom: 12, fontWeight: '500' },
    loader: { marginTop: 100, alignSelf: 'center' },
    previewCard: { backgroundColor: colors.background, borderRadius: 0, padding: 0, marginTop: 0, marginBottom: 12, position: 'relative', overflow: 'hidden' },
    previewTitle: { fontSize: 22, fontWeight: 'bold', color: colors.textPrimary, marginBottom: 8 },
    chatSection: { width: '100%', marginBottom: 0 },
    chatRowLeft: { width: '100%', alignItems: 'flex-start', marginBottom: 0 },
    chatRowRight: { width: '100%', alignItems: 'flex-end', marginBottom: 0 },
    chatBubbleLeft: { backgroundColor: colors.surfaceAlt, borderRadius: 14, borderTopLeftRadius: 4, paddingTop: 0, paddingBottom: 0, paddingHorizontal: 0, maxWidth: '80%', overflow: 'hidden' },
    chatBubbleRight: { backgroundColor: colors.border, borderRadius: 14, borderTopRightRadius: 4, paddingVertical: 0, paddingHorizontal: 0, maxWidth: '80%', overflow: 'hidden' },
    chatText: { color: colors.textPrimary, fontSize: 13, lineHeight: 18 },
    chatTextRight: { color: colors.textPrimary, fontSize: 13, lineHeight: 18, marginBottom: 2 },
    chatCoordsText: { color: colors.textSecondary, fontSize: 11, marginBottom: 2 },
    chatStreetImage: { width: '100%', height: 160, backgroundColor: colors.background },
    videoBubbleContainer: { width: '100%', aspectRatio: 9 / 16, overflow: 'hidden', position: 'relative', backgroundColor: colors.background },
    videoBubbleCamera: { width: '100%', height: '100%' },
    videoBubbleOverlay: { position: 'absolute', top: 8, left: 8, right: 8, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
    videoRecordingBadge: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.55)', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 3 },
    videoRecordingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#EF4444', marginRight: 5 },
    videoRecordingText: { color: colors.textPrimary, fontSize: 11, fontWeight: '700', letterSpacing: 0.5 },
    videoFlipBtn: { position: 'absolute', top: '50%', left: '50%', marginTop: -18, marginLeft: -18, width: 36, height: 36, justifyContent: 'center', alignItems: 'center' },
    videoFullscreenOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, zIndex: 200, backgroundColor: colors.background },
    videoFullscreenBadge: { position: 'absolute', top: 60, left: 16, flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.55)', borderRadius: 4, paddingHorizontal: 6, paddingVertical: 3 },
    videoFullscreenFlipBtn: { position: 'absolute', top: '50%', left: '50%', marginTop: -35, marginLeft: -35, width: 70, height: 70, justifyContent: 'center', alignItems: 'center' },
    chatHighlight: { color: colors.accentLight, fontWeight: '700' },
    quickResponseContainer: { width: '100%', marginBottom: 12 },
    quickResponseContent: { flexDirection: 'row', gap: 8, paddingHorizontal: 2 },
    quickResponseButton: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12 },
    quickResponseText: { color: colors.textSecondary, fontSize: 12, fontWeight: '500' },
    bottomInputArea: { backgroundColor: colors.background, paddingHorizontal: 10, paddingTop: 6, paddingBottom: 8, zIndex: 100, elevation: 100 },
    chatInputWrap: { width: '100%', alignItems: 'stretch', position: 'relative' },
    chatInput: { backgroundColor: colors.inputBackground, borderColor: colors.inputBorder, borderWidth: 1, borderRadius: 12, color: colors.inputText, fontSize: 13, paddingHorizontal: 12, paddingRight: 42, paddingVertical: 10, minHeight: 44 },
    chatSendIconButton: { position: 'absolute', right: 10, top: 0, bottom: 0, justifyContent: 'center', paddingHorizontal: 2 },
    chatSendIcon: { color: colors.textPrimary, fontSize: 18, fontWeight: '700' },
    previewActions: { width: '100%', marginTop: 16 },
    imageLabel: { fontSize: 13, fontWeight: '600', color: colors.textPrimary, marginBottom: 8, alignSelf: 'flex-start' },
    mapImage: { width: '100%', height: 300, borderRadius: 0, marginBottom: 0 },
    closeButton: { backgroundColor: colors.accent, paddingVertical: 14, paddingHorizontal: 32, borderRadius: 10, width: '100%', alignItems: 'center', marginBottom: 8 },
    closeButtonText: { color: colors.textPrimary, fontSize: 16, fontWeight: 'bold' },
    addressCarouselContainer: { position: 'relative', width: '100%', marginBottom: 12 },
    streetViewImage: { width: '100%', height: 320, borderRadius: 0 },
    popupOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'transparent', justifyContent: 'center', alignItems: 'center', padding: 16, zIndex: 50 },
    popupContainer: { width: '95%', maxHeight: '88%', borderRadius: 16, elevation: 10, shadowColor: colors.background, shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.4, shadowRadius: 8, marginBottom: 60 },
    popupHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
    popupTitle: { color: colors.textPrimary, fontSize: 16, fontWeight: '700' },
    popupCloseBtn: { padding: 4 },
    mapSettingsBar: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8, flexWrap: 'wrap' },
    mapTypeToggle: { flexDirection: 'row', backgroundColor: colors.surfaceAlt, borderRadius: 14, borderWidth: 1, borderColor: colors.borderLight },
    mapTypeToggleBtn: { paddingHorizontal: 10, paddingVertical: 4, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'transparent', borderRadius: 13 },
    mapTypeToggleBtnActive: { backgroundColor: colors.accent, borderColor: 'rgba(255,255,255,0.3)', borderWidth: 1.5 },
    mapTypeToggleBtnText: { color: colors.textSecondary, fontSize: 13, fontWeight: '500' },
    mapTypeToggleBtnTextActive: { color: colors.textPrimary },
    mapSettingsChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: colors.surfaceAlt, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 14, borderWidth: 1, borderColor: colors.borderLight },
    mapSettingsChipActive: { backgroundColor: colors.accent, borderColor: 'rgba(255,255,255,0.3)', borderWidth: 1.5 },
    mapSettingsChipText: { color: colors.textSecondary, fontSize: 12, fontWeight: '500' },
    mapSettingsChipTextActive: { color: colors.textPrimary },
    mapSearchBox: { paddingHorizontal: 0, paddingBottom: 8, paddingTop: 8 },
    mapSearchRow: { flexDirection: 'row', alignItems: 'flex-start', backgroundColor: colors.surfaceAlt, borderColor: colors.borderLight, borderWidth: 1, borderRadius: 14, paddingHorizontal: 12, paddingVertical: 5, minHeight: 34 },
    mapSearchAddressInput: { flex: 1, color: colors.inputText, fontSize: 13, padding: 0, textAlign: 'center' as const },
    mapLocationBar: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 0, paddingBottom: 12, flexWrap: 'wrap' },
    mapFloorPillDivider: { width: 1, alignSelf: 'stretch', backgroundColor: colors.borderLight, marginVertical: 4 },
    mapFloorPillInput: { color: colors.inputText, fontSize: 13, paddingHorizontal: 10, paddingVertical: 4, minWidth: 36, textAlign: 'center' },
  });
