import React, { useState } from 'react';
import type { EmergencyCallMessage, EmergencyMessageStateSetter } from './emergencyCallMessageTypes';
import { View, TouchableOpacity, Image, Animated, StyleSheet } from 'react-native';
import AppText from '../../components/AppText';
import { Camera } from 'react-native-vision-camera';
import AppVideo from '../../components/AppVideo';
// @ts-ignore
import { Ionicons } from '@expo/vector-icons';
import VideoConnectingBubble from './VideoConnectingBubble';
import { PsapVideoWebView } from './PsapVideoWebView';

const Text = AppText;
const VIDEO_REQUEST_MSG =
  'Can we connect through video so i can show you live feed of the emergency';

/** True when the message was auto-generated by the app system, NOT a user action or real SMS. */
const isAutoMsg = (msg: EmergencyCallMessage): boolean => {
  if (!msg) return false;
  // User-tapped emergency type buttons are deliberate user actions, not automated.
  if (msg.type === 'user') return false;
  // Location, relocation, video, psap-video — all system-generated.
  if (msg.type !== 'chat') return true;
  // Chat messages without a real timestamp are system error/info messages.
  if (!(msg as any).timestamp && !(msg as any).date) return true;
  return false;
};

export const MessageDeliveryMetadata: React.FC<{
  msg: EmergencyCallMessage;
  fs: (n: number) => number;
  colors: any;
  outsideBubble?: boolean;
  align?: 'left' | 'right';
  inset?: number;
  topInset?: number;
  bottomInset?: number;
}> = ({ msg, fs, colors, outsideBubble = false, inset = 12, topInset = 4, bottomInset = 6 }) => {
  const ts = (msg as any).timestamp || (msg as any).date || (msg as any).sessionId || (isAutoMsg(msg) ? Date.now() : null);
  const d = ts ? new Date(ts) : null;
  const timeStr = (d && !isNaN(d.getTime()))
    ? (d.toDateString() === new Date().toDateString()
        ? d.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })
        : d.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' }))
    : '';
  const auto = isAutoMsg(msg);
  if (!auto && !timeStr) return null;
  const label = [auto ? 'Automated' : '', timeStr].filter(Boolean).join(' · ');
  void label;
  const text = (
    <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 6, paddingTop: topInset, paddingBottom: bottomInset, paddingLeft: inset, paddingRight: inset }}>
      {auto && (
        <View style={{ backgroundColor: '#DC2626', borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 }}>
          <AppText style={{ color: '#FFFFFF', fontSize: fs(8), fontWeight: '700', lineHeight: fs(11) }}>Automated</AppText>
        </View>
      )}
      {!!timeStr && (
        <AppText style={{ color: auto ? '#FFFFFF' : (colors.textMuted || colors.textSecondary), fontSize: fs(9), lineHeight: fs(12) }}>
          {timeStr}
        </AppText>
      )}
    </View>
  );
  if (outsideBubble) {
    return (
      <View style={{ width: '100%', alignItems: 'flex-end', paddingTop: topInset, paddingBottom: bottomInset, paddingLeft: inset, paddingRight: inset }}>
        {text}
      </View>
    );
  }
  return text;
};

interface Props {
  chatMessages: EmergencyCallMessage[];
  lastLocationMsgIdx: number;
  // Optional slice of chatMessages to render. Used by the SMS-first layout
  // in EmergencyCallScreen to render messages added BEFORE the location preview
  // appeared above the preview card, and messages added AFTER below it,
  // preserving chronological order. When omitted, the full array renders.
  sliceStart?: number;
  sliceEnd?: number;
  baseIndex?: number;
  openLocationNavigator: () => void;
  handleRelocationResponse: (idx: number, response: 'yes' | 'no') => void;
  // Camera props
  hasCamPermission: boolean;
  activeCamDevice: any;
  cameraIsActiveProp: boolean;
  cameraRef: React.RefObject<any>;
  cameraReadyRef: React.MutableRefObject<boolean>;
  hasMicPermission: boolean;
  onCameraInitialized: () => void;
  videoCollapseAnim: Animated.Value;
  videoBubbleRef: React.RefObject<any>;
  videoBubbleRendered: boolean;
  setVideoBubbleRendered: (v: boolean) => void;
  expandedAnims: Set<Animated.Value>;
  expandOne: (anim: Animated.Value, ref?: React.RefObject<any>) => void;
  setVideoExpanded: (v: boolean) => void;
  takePictureAndSend: () => void;
  takingPicture: boolean;
  startCameraRecording: () => void;
  stopCameraRecording: () => void;
  videoStreamingActive: boolean;
  setVideoStreamingActive: (v: boolean) => void;
  videoSessionCount: React.MutableRefObject<number>;
  videoBubblePushedRef: React.MutableRefObject<boolean>;
  getRelocationAnim: (idx: number) => Animated.Value;
  relocationThumbRefs: React.MutableRefObject<Record<number, any>>;
  getChatImageAnim: (idx: number) => Animated.Value;
  chatImageThumbRefs: React.MutableRefObject<Record<number, any>>;
  recordingDotOpacity: Animated.Value;
  activeCamera: 'front' | 'back';
  setActiveCamera: (c: 'front' | 'back') => void;
  isLandscape: boolean;
  setChatMessages: EmergencyMessageStateSetter;
  detectedLocation: any;
  sendPsapMessage: (msg: string, lat?: number, lng?: number) => Promise<boolean>;
  onImagePress?: (messageId: string) => void;
  textScale: number;
  colors: any;
  collapseH: number;
  btnLabel: any;
  fs: (n: number) => number;
  styles: any;
}

export const EmergencyCallMessageList: React.FC<Props> = ({
  chatMessages, lastLocationMsgIdx, sliceStart, sliceEnd, openLocationNavigator, handleRelocationResponse,
  hasCamPermission, activeCamDevice, cameraIsActiveProp, cameraRef, cameraReadyRef, hasMicPermission,
  onCameraInitialized, videoCollapseAnim, videoBubbleRef, videoBubbleRendered,
  setVideoBubbleRendered, expandedAnims, expandOne, setVideoExpanded,
  takePictureAndSend, takingPicture, startCameraRecording, stopCameraRecording,
  videoStreamingActive, setVideoStreamingActive, videoSessionCount, videoBubblePushedRef,
  getRelocationAnim, relocationThumbRefs, getChatImageAnim, chatImageThumbRefs,
  recordingDotOpacity, setActiveCamera,
  isLandscape, setChatMessages, detectedLocation, sendPsapMessage, colors, collapseH, btnLabel, fs, styles,
  onImagePress, baseIndex = 0,
}: any) => {
  const start = sliceStart ?? 0;
  const end = sliceEnd ?? chatMessages.length;
  const visible = chatMessages.slice(start, end);
  const latestVideoIdx = chatMessages.reduce(
    (last: number, item: EmergencyCallMessage, itemIdx: number) => item.type === 'video' ? baseIndex + itemIdx : last,
    -1,
  );
  return (
    <>
      {visible.map((msg: EmergencyCallMessage, localIdx: number) => {
        // Preserve global idx so relocationThumbRefs / getRelocationAnim /
        // handleRelocationResponse keep working when the list is sliced.
        const idx = baseIndex + start + localIdx;
        // History-only messages (e.g. the detected address snapshot) are saved
        // to the session for the reveal UI but never rendered in the live chat,
        // where the interactive location preview card shows them instead.
        if ((msg as any).historyOnly) return null;

        // ── PSAP Video Session WebView ──────────────────────────────────────────
        if (msg.type === 'psap-video') {
          return (
            <PsapVideoWebView
              key={idx}
              url={(msg as any).url}
              colors={colors}
              fs={fs}
              onDismiss={() =>
                setChatMessages((prev) =>
                  prev.filter(
                    (m: any) => !(m.type === 'psap-video' && m.url === (msg as any).url),
                  )
                )
              }
            />
          );
        }

        const hasImage = (msg.type === 'location' || msg.type === 'chat') && !!msg.imageUrl;
        const messageId = (msg as any).id || `e911-media-${idx}`;
        if (msg.type === 'user') {
          return (
            <View key={idx} style={[styles.previewCard, { marginBottom: 12 }]}>
              <View style={styles.chatSection}><View style={styles.chatRowRight}>
                <View style={styles.chatBubbleRight}>
                  <Text style={[styles.chatTextRight, { paddingHorizontal: 12, paddingVertical: 10, marginBottom: 0, fontSize: fs(13), lineHeight: fs(18) }]}>{msg.text}</Text>
                </View>
              </View></View>
            </View>
          );
        }
        if (msg.type === 'video') {
          const isLatestVideo = idx === latestVideoIdx;
          const videoStopped = !!msg.stopped;
          const restartAvailable = isLatestVideo && videoStopped && !msg.restartConsumed;
          const showLivePreview = isLatestVideo && !videoStopped && hasCamPermission && activeCamDevice;
          const showActiveControls = showLivePreview && videoStreamingActive;
          const hasVideoContentBelowText = showLivePreview || restartAvailable;
          const stopThisRecording = async () => {
            await stopCameraRecording();
            setVideoStreamingActive(false);
            setChatMessages((prev) => prev
              .filter((m: any) => m.type !== 'video-connecting')
              .map((m: any, i: number) => i === idx ? { ...m, stopped: true } : m));
          };
          const restartRecording = () => {
            const nextSessionId = Date.now();
            videoSessionCount.current += 1;
            videoBubblePushedRef.current = true;
            cameraReadyRef.current = false;
            setChatMessages((prev) => {
              const next = prev.map((m: any, i: number) => (
                i === idx ? { ...m, restartConsumed: true } : m
              ));
              next.push({ type: 'video', sessionId: nextSessionId, timestamp: nextSessionId });
              next.push({ type: 'video-connecting', sessionId: nextSessionId, timestamp: nextSessionId });
              return next;
            });
            setVideoStreamingActive(true);
            sendPsapMessage(VIDEO_REQUEST_MSG, detectedLocation?.latitude, detectedLocation?.longitude).catch(() => {});
            startCameraRecording();
          };
          return (
            <View key={idx} ref={videoBubbleRef} style={[styles.previewCard, { marginBottom: 12 }]} onLayout={() => { if (!videoBubbleRendered) setVideoBubbleRendered(true); }}>
              <View style={styles.chatSection}><View style={styles.chatRowRight}>
                <View style={styles.chatBubbleRight}>
                  {hasCamPermission && activeCamDevice ? (
                    <>
                      <Text style={[styles.chatTextRight, { paddingHorizontal: 12, paddingTop: 10, paddingBottom: hasVideoContentBelowText ? 0 : 10, marginBottom: 0, fontSize: fs(12), lineHeight: fs(18) }]}>Here's a live feed of the emergency</Text>
                      {showLivePreview ? (
                        <Animated.View style={{ maxHeight: videoCollapseAnim.interpolate({ inputRange: [0, 1], outputRange: [0, 600] }), overflow: 'hidden' }}>
                          <TouchableOpacity activeOpacity={0.9} onPress={() => { if (!expandedAnims.has(videoCollapseAnim)) expandOne(videoCollapseAnim, videoBubbleRef); else setVideoExpanded(true); }} style={{ borderRadius: 8, overflow: 'hidden', marginHorizontal: 12, marginTop: 10, marginBottom: 0 }}>
                            <View style={[styles.videoBubbleContainer, { aspectRatio: isLandscape ? 16 / 9 : 9 / 16 }]}>
                              <Camera ref={cameraRef} style={StyleSheet.absoluteFill} device={activeCamDevice} isActive={cameraIsActiveProp} photo video audio={hasMicPermission} outputOrientation="device" onInitialized={onCameraInitialized} onError={(e: any) => { if (e.code !== 'system/camera-is-restricted') console.error('Camera error:', e); }} androidPreviewViewType="texture-view" />
                              <View style={styles.videoBubbleOverlay}>
                                <View style={styles.videoRecordingBadge}>
                                  <Animated.View style={[styles.videoRecordingDot, { opacity: recordingDotOpacity }]} />
                                  <Text style={styles.videoRecordingText}>Live</Text>
                                </View>
                                <TouchableOpacity onPress={(e: any) => { e.stopPropagation(); setVideoExpanded(true); }} activeOpacity={0.7} style={{ width: 32, height: 32, borderRadius: 16, backgroundColor: 'rgba(0,0,0,0.55)', justifyContent: 'center', alignItems: 'center' }}>
                                  <Ionicons name="expand-outline" size={18} color="#FFF" />
                                </TouchableOpacity>
                              </View>
                              <TouchableOpacity style={styles.videoFlipBtn} onPress={(e: any) => { e.stopPropagation(); setActiveCamera((p: any) => p === 'front' ? 'back' : 'front'); }} activeOpacity={0.7}>
                                <Ionicons name="camera-reverse-outline" size={28} color="rgba(255,255,255,0.6)" />
                              </TouchableOpacity>
                            </View>
                          </TouchableOpacity>
                        </Animated.View>
                      ) : null}
                      {showActiveControls && (
                        <Animated.View style={{ maxHeight: videoCollapseAnim.interpolate({ inputRange: [0, 0.15, 1], outputRange: [collapseH, 0, 0] }), opacity: videoCollapseAnim.interpolate({ inputRange: [0, 0.15, 1], outputRange: [1, 0, 0] }), overflow: 'hidden' }}>
                          <TouchableOpacity onPress={() => expandOne(videoCollapseAnim, videoBubbleRef)} activeOpacity={0.7} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, marginTop: 10, marginHorizontal: 12, alignSelf: 'stretch', alignItems: 'center' }}>
                            <Text style={btnLabel}>View live streaming video</Text>
                          </TouchableOpacity>
                        </Animated.View>
                      )}
                      {showActiveControls ? (
                        <>
                          <TouchableOpacity onPress={takePictureAndSend} disabled={takingPicture} activeOpacity={0.7} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, marginTop: 10, marginHorizontal: 12, alignSelf: 'stretch', alignItems: 'center', opacity: takingPicture ? 0.5 : 1 }}>
                            <Text style={btnLabel}>{takingPicture ? 'Taking picture...' : 'Take a picture and send'}</Text>
                          </TouchableOpacity>
                          <TouchableOpacity onPress={stopThisRecording} activeOpacity={0.7} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, marginTop: 10, marginHorizontal: 12, marginBottom: 10, alignSelf: 'stretch', alignItems: 'center' }}>
                            <Text style={btnLabel}>Stop video streaming</Text>
                          </TouchableOpacity>
                        </>
                      ) : restartAvailable ? (
                        <TouchableOpacity onPress={restartRecording} activeOpacity={0.7} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, marginTop: 10, marginHorizontal: 12, marginBottom: 10, alignSelf: 'stretch', alignItems: 'center' }}>
                          <Text style={btnLabel}>Restart Recording</Text>
                        </TouchableOpacity>
                      ) : (
                        null
                      )}
                    </>
                  ) : (
                    <Text style={[styles.chatTextRight, { paddingHorizontal: 12, paddingVertical: 10, marginBottom: 0, fontSize: fs(12), lineHeight: fs(18) }]}>Connecting to camera...</Text>
                  )}
                  <MessageDeliveryMetadata msg={msg} fs={fs} colors={colors} />
                </View>
              </View></View>
            </View>
          );
        }
        if (msg.type === 'video-connecting') {
          return <VideoConnectingBubble key={`vid-connecting-${idx}`} msg={msg} styles={styles} fs={fs} />;
        }
        return (
          <View key={idx} style={[styles.previewCard, { marginBottom: 12 }]}>
            <View style={styles.chatSection}>
              {msg.type === 'relocation' ? (
                <View style={styles.chatRowLeft}>
                  <View style={[styles.chatBubbleLeft, { paddingTop: 10, paddingBottom: 10, paddingHorizontal: 12 }]}>
                    <Text style={[styles.chatText, { fontSize: fs(13), lineHeight: fs(18) }]}>{msg.text}</Text>
                    {!msg.responded && (
                      <View style={{ marginTop: 10, gap: 8 }}>
                        <TouchableOpacity style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, alignItems: 'center' }} onPress={() => handleRelocationResponse(idx, 'yes')} activeOpacity={0.7}>
                          <Text style={btnLabel}>Yes, that's my new location.</Text>
                        </TouchableOpacity>
                        <TouchableOpacity style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, alignItems: 'center' }} onPress={() => handleRelocationResponse(idx, 'no')} activeOpacity={0.7}>
                          <Text style={btnLabel}>No, I'm still at the same location.</Text>
                        </TouchableOpacity>
                      </View>
                    )}
                    {msg.responded === 'yes' && <Text style={[styles.chatText, { marginTop: 8, color: '#10B981', fontStyle: 'italic', fontSize: fs(13), lineHeight: fs(18) }]}>You confirmed this as your new location.</Text>}
                    {msg.responded === 'no' && <Text style={[styles.chatText, { marginTop: 8, color: '#F59E0B', fontStyle: 'italic', fontSize: fs(13), lineHeight: fs(18) }]}>PSAP notified you're still at your original location.</Text>}
                    <MessageDeliveryMetadata msg={msg} fs={fs} colors={colors} inset={0} />
                  </View>
                </View>
              ) : (msg as any).incoming ? (
                <View style={styles.chatRowLeft}>
                  <View style={[
                    styles.chatBubbleLeft,
                    hasImage
                      ? { paddingTop: 0, paddingBottom: 0, paddingHorizontal: 0 }
                      : { paddingTop: 10, paddingBottom: 10, paddingHorizontal: 12 },
                  ]}>
                    {hasImage && (
                      <MessageMediaPreview
                        uri={msg.imageUrl}
                        mime={(msg as any).mediaMime}
                        onPress={() => onImagePress?.(messageId)}
                      />
                    )}
                    {!!msg.text && (
                      <Text style={[styles.chatText, hasImage ? { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 10, fontSize: fs(13), lineHeight: fs(18) } : { fontSize: fs(13), lineHeight: fs(18) }]}>{msg.text}</Text>
                    )}
                    <MessageDeliveryMetadata msg={msg} fs={fs} colors={colors} inset={hasImage ? 12 : 0} />
                  </View>
                </View>
              ) : (
                <View style={styles.chatRowRight}>
                  <View style={[
                    styles.chatBubbleRight,
                  ]}>
                    {msg.type === 'chat' && hasImage ? null
                      : msg.type === 'location' && msg.locationLine ? (
                        <Text style={[styles.chatTextRight, { paddingHorizontal: 12, paddingTop: 10, paddingBottom: hasImage ? 0 : (idx === lastLocationMsgIdx ? 0 : 10), marginBottom: 0, fontSize: fs(13), lineHeight: fs(18) }]}>
                          {msg.text?.includes('\n') ? <>{msg.text.split('\n').slice(0, -1).join('\n')}{'\n'}This is my current location <Text style={styles.chatHighlight}>{msg.locationLine}</Text></> : <>This is my current location <Text style={styles.chatHighlight}>{msg.locationLine}</Text></>}
                        </Text>
                      ) : (
                        <>
                          <Text style={[styles.chatTextRight, { paddingHorizontal: 12, paddingTop: 10, paddingBottom: (!msg.address && !msg.coords && !hasImage) ? 10 : 0, fontSize: fs(13), lineHeight: fs(18) }]}>{msg.text}</Text>
                          {msg.type === 'location' && msg.address && <Text style={[styles.chatCoordsText, { paddingHorizontal: 12, fontSize: fs(11) }]}>{msg.address}</Text>}
                          {msg.type === 'location' && msg.coords && <Text style={[styles.chatCoordsText, { paddingHorizontal: 12, paddingBottom: hasImage ? 0 : (idx === lastLocationMsgIdx ? 0 : 10), fontSize: fs(11) }]}>{msg.coords}</Text>}
                        </>
                      )}
                    {hasImage && (
                      msg.type === 'chat' ? (
                        <>
                          <Animated.View ref={(el: any) => { chatImageThumbRefs.current[idx] = el; }} style={{ maxHeight: getChatImageAnim(idx).interpolate({ inputRange: [0, 1], outputRange: [0, 500] }), overflow: 'hidden' }}>
                            <View style={{ marginTop: 10, marginHorizontal: 12, marginBottom: 10 }}>
                              <TouchableOpacity activeOpacity={0.9} onPress={() => expandOne(getChatImageAnim(idx), { current: chatImageThumbRefs.current[idx] })} style={{ borderRadius: 8, overflow: 'hidden', backgroundColor: colors.background }}>
                                <Image source={{ uri: msg.imageUrl }} style={{ width: '100%', aspectRatio: 4 / 3, backgroundColor: colors.background }} resizeMode="cover" />
                              </TouchableOpacity>
                            </View>
                          </Animated.View>
                          <Animated.View style={{ maxHeight: getChatImageAnim(idx).interpolate({ inputRange: [0, 0.15, 1], outputRange: [collapseH, 0, 0] }), opacity: getChatImageAnim(idx).interpolate({ inputRange: [0, 0.15, 1], outputRange: [1, 0, 0] }), overflow: 'hidden' }}>
                            <TouchableOpacity onPress={() => expandOne(getChatImageAnim(idx), { current: chatImageThumbRefs.current[idx] })} activeOpacity={0.7} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, marginTop: 10, marginHorizontal: 12, marginBottom: !!msg.text ? 0 : 10, alignSelf: 'stretch', alignItems: 'center' }}>
                              <Text style={btnLabel}>View sent image</Text>
                            </TouchableOpacity>
                          </Animated.View>
                          {!!msg.text && (
                            <Text style={[styles.chatTextRight, { paddingHorizontal: 12, paddingTop: 10, paddingBottom: 10, fontSize: fs(13), lineHeight: fs(18) }]}>{msg.text}</Text>
                          )}
                        </>
                      ) : (
                        <>
                          <Animated.View ref={(el: any) => { relocationThumbRefs.current[idx] = el; }} style={{ maxHeight: getRelocationAnim(idx).interpolate({ inputRange: [0, 1], outputRange: [0, 500] }), overflow: 'hidden' }}>
                            <View style={{ marginTop: 10, marginHorizontal: 12, marginBottom: 10 }}>
                              <TouchableOpacity activeOpacity={0.9} onPress={() => expandOne(getRelocationAnim(idx), { current: relocationThumbRefs.current[idx] })} style={{ borderRadius: 8, overflow: 'hidden', backgroundColor: colors.background }}>
                                {msg.mapUrl && (
                                  <Image source={{ uri: msg.mapUrl }} style={{ width: '100%', height: 252, backgroundColor: colors.background }} resizeMode="cover" />
                                )}
                                {msg.imageUrl && (
                                  <Image source={{ uri: msg.imageUrl }} style={{ width: '100%', height: 108, backgroundColor: colors.background }} resizeMode="cover" />
                                )}
                              </TouchableOpacity>
                            </View>
                          </Animated.View>
                          <Animated.View style={{ maxHeight: getRelocationAnim(idx).interpolate({ inputRange: [0, 0.15, 1], outputRange: [collapseH, 0, 0] }), opacity: getRelocationAnim(idx).interpolate({ inputRange: [0, 0.15, 1], outputRange: [1, 0, 0] }), overflow: 'hidden' }}>
                            <TouchableOpacity onPress={() => expandOne(getRelocationAnim(idx), { current: relocationThumbRefs.current[idx] })} activeOpacity={0.7} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, marginTop: 10, marginHorizontal: 12, marginBottom: (msg.type === 'location' && idx === lastLocationMsgIdx) ? 0 : 10, alignSelf: 'stretch', alignItems: 'center' }}>
                              <Text style={btnLabel}>View updated location image</Text>
                            </TouchableOpacity>
                          </Animated.View>
                        </>
                      )
                    )}
                    {msg.type === 'location' && idx === lastLocationMsgIdx && (
                      <TouchableOpacity onPress={openLocationNavigator} activeOpacity={0.7} style={{ backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 8, paddingVertical: 8, paddingHorizontal: 12, marginTop: 10, marginHorizontal: 12, marginBottom: 10, alignSelf: 'stretch', alignItems: 'center' }}>
                        <Text style={btnLabel}>Change location</Text>
                      </TouchableOpacity>
                    )}
                    <MessageDeliveryMetadata msg={msg} fs={fs} colors={colors} align="right" />
                  </View>
                </View>
              )}
            </View>
          </View>
        );
      })}
    </>
  );
};

function MessageMediaPreview({
  uri,
  mime,
  onPress,
}: {
  uri?: string;
  mime?: string;
  onPress?: () => void;
}) {
  const [playing, setPlaying] = useState(false);
  const sourceUri = uri || '';
  const isVideo = mime?.startsWith('video/') || /\.(mp4|m4v|mov|3gp|3gpp|webm)(\?|$)/i.test(sourceUri);

  if (!isVideo) {
    return (
      <TouchableOpacity onPress={onPress} activeOpacity={0.85}>
        <Image source={{ uri: sourceUri }} style={mediaStyles.messageMedia} resizeMode="cover" />
      </TouchableOpacity>
    );
  }

  return (
    <TouchableOpacity
      style={mediaStyles.messageMedia}
      onPress={() => setPlaying((value) => !value)}
      onLongPress={onPress}
      activeOpacity={0.9}
    >
      <AppVideo
        uri={sourceUri}
        style={StyleSheet.absoluteFill}
        contentFit="cover"
        playing={playing}
        nativeControls={false}
        onPlaybackEnd={() => setPlaying(false)}
      />
      {!playing ? (
        <View style={mediaStyles.videoPlayOverlay}>
          <Ionicons name="play" size={22} color="#FFFFFF" />
        </View>
      ) : null}
    </TouchableOpacity>
  );
}

const mediaStyles = StyleSheet.create({
  messageMedia: {
    width: 200,
    height: 200,
    borderRadius: 8,
    marginBottom: 4,
    overflow: 'hidden',
    backgroundColor: '#000000',
  },
  videoPlayOverlay: {
    position: 'absolute',
    left: 76,
    top: 76,
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.55)',
  },
});
