import React from 'react';
import { Image, View } from 'react-native';
import AppText from '../../components/AppText';
import type { EmergencyCallSession } from './emergencyCallSessionStore';

const Text = AppText;

interface Props {
  revealedSessions: EmergencyCallSession[];
  emergencyNumber: string;
  colors: any;
  fs: (n: number) => number;
}

const sessionLabel = (s: EmergencyCallSession) => {
  try {
    const d = new Date(s.startedAt);
    return d.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
  } catch { return 'Previous session'; }
};

const formatTime = (dateMs: number): string => {
  try {
    if (!dateMs || dateMs <= 0) return '';
    const d = new Date(dateMs);
    const isToday = d.toDateString() === new Date().toDateString();
    return isToday
      ? d.toLocaleTimeString(undefined, { hour: 'numeric', minute: '2-digit' })
      : d.toLocaleString(undefined, { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit' });
  } catch { return ''; }
};

/** Get display text for any message type. */
const msgBody = (m: any): string => {
  if (m?.text) return m.text;
  if (m?.body) return m.body;
  switch (m?.type) {
    case 'location':   return m?.locationLine ? `Current location: ${m.locationLine}` : 'Location update sent.';
    case 'relocation': return m?.address ? `Possible new location: ${m.address}` : 'Possible new location detected.';
    case 'video':      return "Here's a live feed of the emergency";
    case 'video-connecting': return '';
    case 'psap-video': return `Dispatcher video invite: ${m.url || ''}`.trim();
    default:           return m?.address || m?.locationLine || m?.coords || '';
  }
};

/** True when the message was auto-generated by the app system, not a user action or real SMS. */
const isAutomated = (m: any): boolean => {
  if (!m) return false;
  // User-tapped emergency type buttons are deliberate user actions.
  if (m.type === 'user') return false;
  // Non-chat types are always automated.
  if (m.type && m.type !== 'chat') return true;
  // Chat messages without a real timestamp are system-generated.
  if (m.type === 'chat' && !m.timestamp && !m.date) return true;
  // Outgoing SMS sent by the app (e.g. "Automated location (not yet confirmed
  // by caller): …") are system-generated even though they have real timestamps.
  const text = String(m?.text || m?.body || '');
  if (!m.incoming && text.startsWith('Automated location')) return true;
  return false;
};

export const EmergencyCallHistory: React.FC<Props> = ({ revealedSessions, colors, fs }) => {
  if (!revealedSessions || revealedSessions.length === 0) return null;

  return (
    <View>
      {revealedSessions.map((s) => (
        <View key={s.id} style={{ marginBottom: 10, paddingHorizontal: 10, opacity: 0.85 }}>
          {/* Session header */}
          <View style={{ alignItems: 'center', marginVertical: 6 }}>
            <Text style={{ color: colors.textSecondary, fontSize: fs(10) }}>{sessionLabel(s)}</Text>
          </View>
          {/* Messages */}
          {s.messages.map((m: any, i: number) => {
            if (!m) return null;
            const body = msgBody(m);
            const hasImage = !!(m?.imageUrl || m?.imageUri);
            if (!body && !hasImage) return null;
            const auto = isAutomated(m);
            const incoming = m?.incoming || m?.type === 1 || false;
            const footerInset = hasImage ? 12 : 0;

            return (
              <View key={m?.id || i} style={{ alignSelf: 'stretch', alignItems: incoming ? 'flex-start' : 'flex-end', marginVertical: 3 }}>
                <View style={{
                  maxWidth: '82%',
                  backgroundColor: incoming ? colors.surface : colors.surfaceAlt,
                  borderRadius: 14,
                  borderTopLeftRadius: incoming ? 4 : 14,
                  borderTopRightRadius: incoming ? 14 : 4,
                  paddingHorizontal: hasImage ? 0 : 12,
                  paddingVertical: hasImage ? 0 : 8,
                  overflow: 'hidden',
                }}>
                  {hasImage && (
                    <Image source={{ uri: m.imageUrl || m.imageUri }} style={{ width: 200, height: 200, borderRadius: 8, marginBottom: 4, backgroundColor: colors.background }} resizeMode="cover" />
                  )}
                  {!!body && (
                    <Text style={{
                      color: incoming ? colors.textPrimary : colors.textSecondary,
                      fontSize: fs(12),
                      lineHeight: fs(17),
                      paddingHorizontal: hasImage ? 12 : 0,
                      paddingTop: hasImage ? 6 : 0,
                      paddingBottom: auto || hasImage ? 6 : 10,
                    }}>{body}</Text>
                  )}
                  {/* Footer: timestamp + optional automated badge */}
                  <View style={{ flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 6, paddingTop: 4, paddingBottom: 6, paddingLeft: footerInset, paddingRight: footerInset }}>
                    {auto && (
                      <View style={{ backgroundColor: '#DC2626', borderRadius: 4, paddingHorizontal: 5, paddingVertical: 2 }}>
                        <Text style={{ color: '#FFFFFF', fontSize: fs(8), fontWeight: '700', lineHeight: fs(11) }}>Automated</Text>
                      </View>
                    )}
                    <Text style={{ color: auto ? '#FFFFFF' : (colors.textMuted || colors.textSecondary), fontSize: fs(9), lineHeight: fs(12) }}>
                      {formatTime(m?.timestamp || m?.date || s.startedAt || 0)}
                    </Text>
                  </View>
                </View>
              </View>
            );
          })}
        </View>
      ))}
    </View>
  );
};
