import { StyleSheet } from 'react-native';

export const silentCallChatStyles = StyleSheet.create({
  container: { flex: 1 },
  callActiveBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#1E3A2F',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginBottom: 6,
  },
  liveDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: '#4ADE80',
    marginRight: 6,
  },
  callActiveText: { color: '#86EFAC', fontWeight: '600' },
  messageList: { flex: 1, marginBottom: 6 },
  messageContent: { paddingVertical: 4, gap: 6 },
  msgBubble: { borderRadius: 10, padding: 10, maxWidth: '85%' },
  userBubble: {
    backgroundColor: '#1D4ED8',
    alignSelf: 'flex-end',
    marginLeft: '15%',
  },
  dispatcherBubble: {
    backgroundColor: '#374151',
    alignSelf: 'flex-start',
    marginRight: '15%',
  },
  systemBubble: {
    backgroundColor: 'transparent',
    alignSelf: 'center',
    paddingVertical: 4,
  },
  senderLabel: { color: '#9CA3AF', marginBottom: 2, fontWeight: '600' },
  msgText: { color: '#F9FAFB', lineHeight: 18 },
  systemText: { color: '#9CA3AF', fontStyle: 'italic', textAlign: 'center' },
  ttsLabel: { color: '#93C5FD', marginTop: 4, fontStyle: 'italic' },
  quickBar: { maxHeight: 42, marginBottom: 6 },
  quickBtn: {
    backgroundColor: '#7C2D12',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginRight: 8,
  },
  quickText: { color: '#FECACA', fontWeight: '600' },
  inputRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  input: {
    flex: 1,
    backgroundColor: '#1F2937',
    borderRadius: 10,
    color: '#F9FAFB',
    paddingHorizontal: 12,
    paddingVertical: 8,
    maxHeight: 80,
    borderWidth: 1,
    borderColor: '#374151',
  },
  sendBtn: {
    backgroundColor: '#2563EB',
    borderRadius: 10,
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  sendDisabled: { opacity: 0.4 },
  sendIcon: { color: '#FFF', fontSize: 18 },
});
