const BASE_OFFLINE_UI_PHRASES: string[] = [
  'Settings',
  'Theme Mode',
  'Auto',
  'Light',
  'Dark',
  'Preferred Language',
  'Select Language',
  'Download Offline Language Pack',
  'Offline language pack installed',
  'Downloading offline pack...',
  'Offline pack download failed',
  'Deaf or Mute',
  'Text Size',
  'Street View Controls',
  'Emergency Settings',
  'Emergency Contacts',
  'Saved Addresses',
  'Include in Emergency Contact SMS',
  'Save Changes',
  'Add Address',
  'Send SMS alerts during emergency',
  'Check-In Active',
  'Schedule',
  'Call 911',
  'Alert Loved Ones',
  'When I Miss a Check-In',
  'Information for Dispatchers',
  'Medical Info',
  'Notification Radius',
  'Enable Nearby Medical Alerts',
  'Home',
  'Profile',
  'Map',
  'Notifications',
  'Back',
  'Cancel',
  'Save',
  'Continue',
  'Loading...',
  'Selected',
  'Language',
  'Emergency',
  'Call active',
  'Type message (will be spoken to dispatcher)...',
  'Download required before selecting',
  'Downloading...',
  'Speak and type in your language during 911 calls - messages are automatically translated to English for the dispatcher, and the dispatcher\'s English responses are translated back for you',
  'Theme, language, deaf/mute mode, street view controls',
  'People who receive SMS alerts when you trigger an emergency',
  'Home, work, or other locations shared with dispatchers during an emergency',
  'Switching automatically based on ambient light sensor',
  'Activates silent call mode on every 911 call',
  'Scales all text across the entire app',
  'Buttons + Joystick',
  'Dual Joysticks (Default)',
  'Edge Buttons + Center',
  'Arrow buttons for movement, joystick for rotation',
  'Left joystick moves, right joystick rotates',
  'Buttons on edges, subtle joystick in center',
  'GPS Calibration',
  'Save and calibrate your exact position so emergency dispatch receives better location accuracy.',
  'View Recordings',
  'Review, keep, or delete emergency recordings and manage your recording retention settings.',
  'Check-In Settings',
  'Configure automatic safety check-ins, escalation timing, and who gets notified if you miss one.',
  'Call Start Selfie',
  'When enabled, the app captures a front-facing selfie as you call 911 and sends it with your saved profile photo to dispatch for faster identification.',
  'Submit certifications, choose your response radius, and manage nearby medical emergency alerts.',
  'Phone not verified',
];

export const OFFLINE_UI_PHRASES: string[] = Array.from(
  new Set(BASE_OFFLINE_UI_PHRASES),
);
