package com.contact.app

import com.facebook.react.ReactPackage

/**
 * Single source of truth for all ported React Native native packages.
 * Wire this into ReactApplication.getPackages() once the RN/Expo layer
 * is set up (e.g. in MainApplication when generated by Expo prebuild).
 *
 * Usage:
 *   override fun getPackages(): List<ReactPackage> =
 *       PackageList(this).packages + E911NativePackages.all
 */
object E911NativePackages {
    fun all(): List<ReactPackage> = listOf(
        DirectSmsPackage(),
        DirectMmsPackage(),
        E911DetectorPackage(),
        SmsObserverPackage(),
        SmsReaderPackage(),
        SmsWriterPackage(),
        CustomContactPackage(),
        InCallPackage(),
        CallAudioPackage(),
        PendingSharePackage(),
        ShareFilePackage(),
    )
}
