import { StyleSheet } from 'react-native';

export default function makeEditProfileStyles(colors: any, topInset: number) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      paddingTop: topInset + 8,
      paddingHorizontal: 16,
      paddingBottom: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      borderBottomWidth: 1,
      borderBottomColor: colors.border,
      backgroundColor: colors.surface,
    },
    headerTitle: { fontSize: 18, fontWeight: '700', color: colors.textPrimary },
    backButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    backGlyph: { fontSize: 30, lineHeight: 30, color: colors.textPrimary },
    infoButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    body: { paddingBottom: 36 },
    sectionLabel: {
      color: colors.textSecondary,
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
      marginTop: 14,
      marginBottom: 6,
      paddingHorizontal: 20,
    },
    section: {
      backgroundColor: colors.surface,
      borderTopWidth: 1,
      borderBottomWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 20,
      paddingVertical: 10,
      marginTop: 12,
    },
    sectionFirst: { marginTop: 12 },
    fieldBlock: {
      paddingVertical: 10,
    },
    photoSection: { alignItems: 'center', paddingVertical: 8 },
    photoCircle: {
      width: 88,
      height: 88,
      borderRadius: 44,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1.5,
      borderColor: colors.borderLight,
      alignItems: 'center',
      justifyContent: 'center',
      overflow: 'hidden',
      marginBottom: 12,
    },
    photoImage: { width: '100%', height: '100%' },
    photoAddText: { color: colors.textMuted, fontSize: 40, fontWeight: '300' },
    photoExplain: { color: colors.textMuted, fontSize: 13, lineHeight: 18, textAlign: 'center', paddingHorizontal: 8 },
    label: { color: colors.textSecondary, fontSize: 13, marginBottom: 6, marginTop: 0 },
    input: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      color: colors.inputText,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 11,
      fontSize: 16,
    },
    inputMultiline: { minHeight: 88, textAlignVertical: 'top' },
    selectorInput: {
      borderWidth: 1,
      borderColor: colors.inputBorder,
      backgroundColor: colors.inputBackground,
      borderRadius: 10,
      paddingHorizontal: 12,
      paddingVertical: 11,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    selectorInputText: { color: colors.inputText, fontSize: 16 },
    toggleLine: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 2 },
    toggleLabel: { marginBottom: 0, flex: 1, marginRight: 12 },
    segmentToggle: {
      flexDirection: 'row',
      backgroundColor: colors.surfaceAlt,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    segmentToggleButton: {
      paddingHorizontal: 12,
      paddingVertical: 5,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: 'transparent',
      borderRadius: 13,
      minWidth: 48,
    },
    segmentToggleButtonActive: { backgroundColor: colors.accent, borderColor: 'rgba(255,255,255,0.3)', borderWidth: 1.5 },
    segmentToggleText: { color: colors.textSecondary, fontSize: 13, fontWeight: '500' },
    segmentToggleTextActive: { color: '#FFFFFF' },
    hint: { color: colors.textMuted, marginTop: 16, marginHorizontal: 20, fontSize: 12, lineHeight: 18 },
    toggleRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', paddingVertical: 10 },
    toggleRowLeft: { flex: 1, marginRight: 12 },
    toggleRowLabel: { color: colors.textPrimary, fontSize: 15, fontWeight: '500', marginBottom: 4 },
    toggleRowDesc: { color: colors.textMuted, fontSize: 12, lineHeight: 17 },
    modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center' },
    infoModal: { backgroundColor: colors.surface, borderRadius: 12, padding: 24, paddingTop: 16, width: '85%', maxWidth: 380, borderWidth: 1, borderColor: colors.border },
    infoClose: { alignSelf: 'flex-end', padding: 4, marginBottom: 8 },
    infoText: { color: colors.textPrimary, fontSize: 15, lineHeight: 22 },
    pickerTitle: { color: colors.textPrimary, fontSize: 17, fontWeight: '700', marginBottom: 12 },
    pickerList: { gap: 8 },
    pickerOption: {
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceAlt,
      borderRadius: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
    },
    pickerOptionActive: { backgroundColor: colors.accent, borderColor: 'rgba(255,255,255,0.3)', borderWidth: 1.5 },
    pickerOptionText: { color: colors.textPrimary, fontSize: 15, fontWeight: '500' },
    pickerOptionTextActive: { color: '#FFFFFF' },
    modalOverlayBottom: { flex: 1, justifyContent: 'center', alignItems: 'center' },
    modalBackdrop: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      backgroundColor: 'rgba(0,0,0,0.6)',
    },
    bottomSheet: {
      backgroundColor: colors.surface,
      borderRadius: 22,
      paddingHorizontal: 24,
      paddingTop: 20,
      paddingBottom: 24,
      borderWidth: 1,
      borderColor: colors.border,
      width: '85%',
      maxWidth: 340,
    },
    unitToggleRow: { marginBottom: 16, alignItems: 'center' },
    wheelRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, marginTop: 6, marginBottom: 12 },
    wheelColumn: {
      height: 220,
      position: 'relative',
      overflow: 'hidden',
      borderRadius: 12,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    wheelContent: { paddingVertical: 88 },
    wheelItem: { height: 44, justifyContent: 'center', alignItems: 'center' },
    wheelItemText: { color: colors.textMuted, fontSize: 22, fontWeight: '500' },
    wheelItemTextActive: { color: colors.textPrimary, fontSize: 24, fontWeight: '700' },
    wheelHighlight: {
      position: 'absolute',
      left: 4,
      right: 4,
      top: 88,
      height: 44,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: 'rgba(255,255,255,0.05)',
    },
    inlineDot: { color: colors.textPrimary, fontSize: 28, fontWeight: '700' },
    inlineUnit: { color: colors.textPrimary, fontSize: 18, fontWeight: '600' },
    sheetActions: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 8 },
    sheetActionBtn: { paddingVertical: 10, paddingHorizontal: 8 },
    sheetActionText: { color: colors.textPrimary, fontSize: 18, fontWeight: '600' },
  });
}
