import { StyleSheet } from 'react-native';
import { AppColors } from '../../utils/themeColors';

export default function makeEmergencyContactsStyles(colors: AppColors, topInset: number) {
  return StyleSheet.create({
    container: { flex: 1, backgroundColor: colors.background },
    header: {
      flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center',
      paddingHorizontal: 16,
      paddingTop: topInset + 8,
      paddingBottom: 12,
      backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border,
    },
    backButton: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
    headerSpacer: { width: 40, height: 40 },
    headerTitle: { fontSize: 18, fontWeight: 'bold', color: colors.textPrimary },
    list: { padding: 16, flexGrow: 1 },
    contactCard: {
      backgroundColor: colors.surface, borderRadius: 12, padding: 16,
      marginBottom: 12, borderWidth: 1, borderColor: colors.border,
    },
    contactHeaderRow: { flexDirection: 'row', alignItems: 'center' },
    contactAvatarWrap: {
      width: 44, height: 44, borderRadius: 22, marginRight: 12,
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.border,
      overflow: 'hidden',
    },
    contactAvatarImage: { width: '100%', height: '100%' },
    contactInfo: { flex: 1, marginRight: 12 },
    contactName: { fontSize: 17, fontWeight: '600', color: colors.textPrimary, marginBottom: 2 },
    contactRelationship: { fontSize: 13, color: colors.textMuted, marginBottom: 2 },
    contactPhone: { fontSize: 14, color: colors.textSecondary, marginBottom: 2 },
    contactEmail: { fontSize: 13, color: colors.textSecondary },
    contactExpandedArea: { marginTop: 10, borderTopWidth: 1, borderTopColor: colors.border, paddingTop: 10 },
    contactPhoneExpanded: { color: colors.textSecondary, fontSize: 14, marginBottom: 4 },
    contactDetailText: { color: colors.textSecondary, fontSize: 13, lineHeight: 18, marginBottom: 4 },
    contactActionsRow: { flexDirection: 'row', justifyContent: 'space-evenly', alignItems: 'center', marginTop: 10 },
    emergencyActionBtn: {
      width: 50, height: 50, borderRadius: 25,
      backgroundColor: colors.surfaceAlt,
      borderWidth: 1, borderColor: colors.borderLight,
      alignItems: 'center', justifyContent: 'center',
    },
    editButton: {
      width: 36, height: 36,
      alignItems: 'center', justifyContent: 'center',
    },
    emptyState: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingVertical: 60 },
    emptyStateText: { fontSize: 18, fontWeight: '600', color: colors.textMuted, marginBottom: 8 },
    emptyStateSubtext: { fontSize: 14, color: colors.textMuted, textAlign: 'center', paddingHorizontal: 40 },
    desc: { fontSize: 14, color: colors.textSecondary, lineHeight: 21, marginBottom: 16, paddingHorizontal: 4 },
    floatingButton: {
      position: 'absolute', bottom: 24, right: 24,
      width: 56, height: 56, borderRadius: 28,
      backgroundColor: colors.accent,
      borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.3)',
      justifyContent: 'center', alignItems: 'center',
      shadowColor: '#000', shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3, shadowRadius: 4, elevation: 8,
    },
    modalContainer: {
      flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'center', alignItems: 'center',
    },
    modalContent: {
      backgroundColor: colors.surface, borderRadius: 12, padding: 24,
      width: '90%', maxWidth: 400, borderWidth: 1, borderColor: colors.border,
    },
    formCard: {
      width: '92%', maxWidth: 420, borderRadius: 12, borderWidth: 1,
      borderColor: colors.border, backgroundColor: colors.surface,
      overflow: 'hidden', maxHeight: '82%',
    },
    formHeader: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
      paddingHorizontal: 16, paddingVertical: 14, borderBottomWidth: 1,
    },
    formHeaderBtn: { minWidth: 48, alignItems: 'center' },
    formTitle: { fontSize: 17, fontWeight: '600', color: colors.textPrimary },
    formSaveBtn: { color: '#60a5fa', fontWeight: '700', fontSize: 16 },
    formScroll: { padding: 12, paddingBottom: 24 },
    modalTitleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 16 },
    modalTitle: { fontSize: 20, fontWeight: 'bold', color: colors.textPrimary },
    modalCloseButton: { padding: 4 },
    modalBigButton: {
      backgroundColor: colors.borderLight,
      borderRadius: 10, paddingVertical: 18,
      borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.3)',
      alignItems: 'center',
    },
    modalBigButtonText: { color: colors.textPrimary, fontSize: 17, fontWeight: '700' },
    modalCancelOnly: {
      marginTop: 20, alignItems: 'center', paddingVertical: 10,
    },
    input: {
      backgroundColor: colors.inputBackground, borderWidth: 1, borderColor: colors.inputBorder,
      borderRadius: 8, padding: 12, fontSize: 16, marginBottom: 12, color: colors.inputText,
    },
    inputMultiline: {
      minHeight: 80,
    },
    formRow: {
      flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderRadius: 10,
      marginBottom: 8, paddingHorizontal: 12,
      backgroundColor: colors.inputBackground, borderColor: colors.inputBorder,
    },
    photoRow: {
      flexDirection: 'row', alignItems: 'center', borderWidth: 1, borderRadius: 10,
      marginBottom: 8, paddingHorizontal: 12, paddingVertical: 10,
      backgroundColor: colors.inputBackground, borderColor: colors.inputBorder,
    },
    profileAvatarWrap: {
      width: 42, height: 42, borderRadius: 21, marginRight: 12,
      alignItems: 'center', justifyContent: 'center',
      backgroundColor: colors.surfaceAlt, borderWidth: 1, borderColor: colors.border,
      overflow: 'hidden',
    },
    profileAvatarImage: { width: '100%', height: '100%' },
    photoRowText: { color: colors.textPrimary, fontSize: 15, fontWeight: '600' },
    formRowIcon: { marginRight: 10, width: 20 },
    formRowInput: {
      flex: 1, color: colors.inputText, fontSize: 15,
      paddingVertical: 10, minHeight: 40,
    },
    formNotesRow: { alignItems: 'flex-start' },
    formNotesInput: { minHeight: 72, textAlignVertical: 'top' },
    inputError: { borderColor: '#DC2626' },
    modalButtons: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 16 },
    modalButton: { flex: 1, padding: 14, borderRadius: 8, alignItems: 'center', marginHorizontal: 6, borderWidth: 1.5, borderColor: 'rgba(255,255,255,0.3)' },
    modalButtonCancel: { backgroundColor: colors.surfaceAlt },
    modalButtonSave: { backgroundColor: colors.accent },
    modalButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
    modalButtonTextCancel: { color: colors.textMuted, fontSize: 16, fontWeight: '600' },
    deleteBtn: {
      flexDirection: 'row', alignItems: 'center', justifyContent: 'center',
      gap: 8, paddingVertical: 14, borderRadius: 10, borderWidth: 1, marginTop: 16, marginBottom: 8,
    },
    deleteBtnText: { color: '#ef4444', fontSize: 15, fontWeight: '600' },
    smsToggleRow: {
      flexDirection: 'row', alignItems: 'center', marginBottom: 8,
    },
    smsToggleRowLast: { marginBottom: 10 },
    formToggleGroup: {
      borderWidth: 1, borderRadius: 10, marginTop: 4, marginBottom: 8,
      paddingHorizontal: 12, paddingTop: 10,
    },
    toggleLabelWrap: { flexDirection: 'row', alignItems: 'center', flex: 1 },
    toggleControlSlot: { width: 52, alignItems: 'flex-end' },
    smsToggleLabel: { color: colors.textPrimary, fontSize: 14, flex: 1 },
  });
}
